In [1]:
import pandas as pd

In [2]:
import os

In [3]:
def extract_results(base_dir):
    all = []
    for item in filter(lambda x: x.endswith(".tsv"), os.listdir(base_dir)):
        all.append(pd.read_csv(os.path.join(base_dir, item), sep="\t"))
    all_df = pd.concat(all)
    return all_df

In [8]:
all_df

,dataset_name,codec_type,codec_args,permutation,num_documents,num_dimensions,total_nnz,avg_components_per_doc,original_memory_bytes,compressed_memory_bytes,component_memory_bytes,compression_ratio,num_queries,k_results,total_search_time_us,avg_time_per_query_us,avg_time_per_document_ns
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,VByteLe,none,none,8841823,28679,1060698636,119.96,8589934672,3778502144,1586370240,2.273370,100,10,2363728.368,23637283.68,2673.350
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,VByteLe,none,graph_bisection,8841823,28679,1060698636,119.96,8589934672,3487078848,1294946944,2.463361,100,10,1901340.392,19013403.91,2150.394
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,Gamma,none,none,8841823,28679,1060698636,119.96,8589934672,3857159880,1665027976,2.227010,100,10,2265364.939,22653649.39,2562.102
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,VByteBe,none,none,8841823,28679,1060698636,119.96,8589934672,3778502144,1586370240,2.273370,100,10,2314462.721,23144627.21,2617.631
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,Gamma,none,metis,8841823,28679,1060698636,119.96,8589934672,3624485720,1432353816,2.369973,100,10,2223428.653,22234286.53,2514.672
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,VByteLe,none,metis,8841823,28679,1060698636,119.96,8589934672,3528954872,1336822968,2.434130,100,10,1994383.500,19943834.99,2255.625
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,Delta,none,none,8841823,28679,1060698636,119.96,8589934672,3709392904,1517261000,2.315725,100,10,2267280.423,22672804.22,2564.268
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,Delta,none,graph_bisection,8841823,28679,1060698636,119.96,8589934672,3367511632,1175379728,2.550826,100,10,2222456.069,22224560.69,2513.572
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,Delta,none,metis,8841823,28679,1060698636,119.96,8589934672,3531117424,1338985520,2.432639,100,10,2251521.588,22515215.87,2546.445
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,Zeta,k=auto,graph_bisection,8841823,28679,1060698636,119.96,8589934672,3240801520,1048669616,2.650559,100,10,1850885.732,18508857.32,2093.330
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,Zeta,k=auto,none,8841823,28679,1060698636,119.96,8589934672,3533408208,1341276304,2.431062,100,10,2010305.986,20103059.85,2273.633
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,VByteBe,none,graph_bisection,8841823,28679,1060698636,119.96,8589934672,3487078848,1294946944,2.463361,100,10,1843721.082,18437210.81,2085.227
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,VByteBe,none,metis,8841823,28679,1060698636,119.96,8589934672,3528954872,1336822968,2.434130,100,10,1944596.531,19445965.30,2199.316
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,Zeta,k=auto,metis,8841823,28679,1060698636,119.96,8589934672,3379882808,1187750904,2.541489,100,10,1941009.531,19410095.30,2195.259
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,Gamma,none,graph_bisection,8841823,28679,1060698636,119.96,8589934672,3418239352,1226107448,2.512971,100,10,2204499.883,22044998.83,2493.264

In [9]:
all_df.sort_values(["codec_type", "permutation"])[["codec_type", "permutation", 'component_memory_bytes', "avg_time_per_query_us", "avg_time_per_document_ns"]]

,codec_type,permutation,component_memory_bytes,avg_time_per_query_us,avg_time_per_document_ns
0,Delta,graph_bisection,1175379728,22224560.69,2513.572
0,Delta,metis,1338985520,22515215.87,2546.445
0,Delta,none,1517261000,22672804.22,2564.268
0,Gamma,graph_bisection,1226107448,22044998.83,2493.264
0,Gamma,metis,1432353816,22234286.53,2514.672
0,Gamma,none,1665027976,22653649.39,2562.102
0,VByteBe,graph_bisection,1294946944,18437210.81,2085.227
0,VByteBe,metis,1336822968,19445965.30,2199.316
0,VByteBe,none,1586370240,23144627.21,2617.631
0,VByteLe,graph_bisection,1294946944,19013403.91,2150.394
0,VByteLe,metis,1336822968,19943834.99,2255.625
0,VByteLe,none,1586370240,23637283.68,2673.350
0,Zeta,graph_bisection,1048669616,18508857.32,2093.330
0,Zeta,metis,1187750904,19410095.30,2195.259
0,Zeta,none,1341276304,20103059.85,2273.633

In [11]:
assert len(pd.unique(all_df['compressed_memory_bytes'] - all_df['component_memory_bytes'])) == 1
values_mem_bytes = pd.unique(all_df['compressed_memory_bytes'] - all_df['component_memory_bytes'])[0]

In [12]:
1586370240	 / 1024**2

1512.8805541992188

In [13]:
log_partitioned_df = extract_results("../log_partitioned")

In [14]:
log_partitioned_df['component_memory_bytes'] = log_partitioned_df['compressed_memory_bytes'] - values_mem_bytes

In [15]:
1508069126.55 / 1024**2

1438.2067933559417

In [16]:
log_partitioned_df[['permutation_strategy', "component_memory_bytes", "avg_time_per_query_ms", "avg_time_per_document_ns"]]

,permutation_strategy,component_memory_bytes,avg_time_per_query_ms,avg_time_per_document_ns
0,NaN,1791273190,2003492.51,226.593
0,Metis,1515112270,1224214.77,138.457
0,GraphBisection,1508069126,1252391.84,141.644