In [1]:
import pandas as pd

In [2]:
import os

In [3]:
def extract_results(base_dir):
    all = []
    for item in filter(lambda x: x.endswith(".tsv"), os.listdir(base_dir)):
        all.append(pd.read_csv(os.path.join(base_dir, item), sep="\t"))
    all_df = pd.concat(all)
    return all_df

In [4]:
all_df = extract_results("../standard_compression_log/")

In [6]:
all_df.sort_values(["codec_type", "bisection"])[["codec_type", "bisection", 'component_memory_bytes', "avg_time_per_query_us", "avg_time_per_document_ns"]]

,codec_type,bisection,component_memory_bytes,avg_time_per_query_us,avg_time_per_document_ns
0,Delta,False,1517261000,21484250.30,2429.844
0,Delta,True,1175379728,19134814.68,2164.126
0,Delta,NaN,1338985520,19965791.07,2258.108
0,Gamma,False,1665027976,22481228.79,2542.601
0,Gamma,True,1226107448,19768044.41,2235.743
0,Gamma,NaN,1432353816,20608761.66,2330.827
0,VByteBe,False,1586370240,23175943.87,2621.173
0,VByteBe,True,1294946944,17848060.21,2018.595
0,VByteLe,False,1586370240,23149254.40,2618.154
0,VByteLe,True,1294946944,19459215.61,2200.815
0,Zeta,False,1341276304,20180509.20,2282.392
0,Zeta,True,1048669616,19008211.48,2149.807
0,Zeta,NaN,1187750904,19497443.56,2205.138

In [11]:
assert len(pd.unique(all_df['compressed_memory_bytes'] - all_df['component_memory_bytes'])) == 1
values_mem_bytes = pd.unique(all_df['compressed_memory_bytes'] - all_df['component_memory_bytes'])[0]

In [12]:
values_mem_bytes

2192131904

In [13]:
log_partitioned_df = extract_results("../log_partitioned")

In [14]:
log_partitioned_df['component_memory_bytes'] = log_partitioned_df['compressed_memory_bytes'] - values_mem_bytes

In [15]:
1508069126.55 / 1024**2

1438.2067933559417

In [16]:
log_partitioned_df[['permutation_strategy', "component_memory_bytes", "avg_time_per_query_ms", "avg_time_per_document_ns"]]

,permutation_strategy,component_memory_bytes,avg_time_per_query_ms,avg_time_per_document_ns
0,NaN,1791273190,1873478.13,211.888
0,Metis,1515112270,1166205.17,131.896
0,GraphBisection,1508069126,1164665.55,131.722