In [1]:
import pandas as pd

In [2]:
import os

In [15]:
def extract_results(base_dir):
    all = []
    for item in filter(lambda x: x.endswith(".tsv"), os.listdir(base_dir)):
        all.append(pd.read_csv(os.path.join(base_dir, item), sep="\t"))
    all_df = pd.concat(all)
    return all_df

In [4]:
all_df = extract_results("../results_and_log_cocondenser/log_codec_cocondenser/")

In [5]:
all_df.sort_values(["codec_type", "permutation"])[["codec_type", "permutation", 'component_memory_bytes', "avg_time_per_query_us", "avg_time_per_document_ns"]]

,codec_type,permutation,component_memory_bytes,avg_time_per_query_us,avg_time_per_document_ns
0,Delta,graph_bisection,1175379728,22224560.69,2513.572
0,Delta,metis,1338985520,22515215.87,2546.445
0,Delta,none,1517261000,22672804.22,2564.268
0,Gamma,graph_bisection,1226107448,22044998.83,2493.264
0,Gamma,metis,1432353816,22234286.53,2514.672
0,Gamma,none,1665027976,22653649.39,2562.102
0,VByteBe,graph_bisection,1294946944,18437210.81,2085.227
0,VByteBe,metis,1336822968,19445965.30,2199.316
0,VByteBe,none,1586370240,23144627.21,2617.631
0,VByteLe,graph_bisection,1294946944,19013403.91,2150.394
0,VByteLe,metis,1336822968,19943834.99,2255.625
0,VByteLe,none,1586370240,23637283.68,2673.350
0,Zeta,graph_bisection,1048669616,18508857.32,2093.330
0,Zeta,metis,1187750904,19410095.30,2195.259
0,Zeta,none,1341276304,20103059.85,2273.633

In [6]:
assert len(pd.unique(all_df['compressed_memory_bytes'] - all_df['component_memory_bytes'])) == 1
values_mem_bytes = pd.unique(all_df['compressed_memory_bytes'] - all_df['component_memory_bytes'])[0]

In [23]:
log_partitioned_df = extract_results("../results_and_log_cocondenser/log_baseline_stremvbyte_cocondenser/")

In [24]:
log_partitioned_df

,dataset_name,permutation,num_documents,num_dimensions,total_nnz,avg_components_per_doc,original_memory_bytes,compressed_memory_bytes,component_memory_bytes,compression_ratio,num_queries,k_results,total_search_time_us,avg_time_per_query_us,avg_time_per_document_ns
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,none,8841823,28679,1060698636,119.96,8589934672,3886574516,1694442612,2.210156,100,10,348828.299,3488282.99,394.521
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,metis,8841823,28679,1060698636,119.96,8589934672,3735811736,1543679832,2.299349,100,10,346532.604,3465326.04,391.924
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,graph_bisection,8841823,28679,1060698636,119.96,8589934672,3712993374,1520861470,2.313480,100,10,356757.455,3567574.54,403.489

In [33]:
log_partitioned_df['component_memory_bytes'] = log_partitioned_df['compressed_memory_bytes'] - values_mem_bytes

In [29]:
1694442612 / 1024**2

1615.9463996887207

In [32]:
log_partitioned_df['component_memory_bytes']

0    1694442612
0    1543679832
0    1520861470
Name: component_memory_bytes, dtype: int64

In [35]:
extract_results("../results_and_log_cocondenser/log_partitioned_cocondenser/")

,dataset_name,permutation_strategy,n_partitions,n_component_bits,num_documents,num_dimensions,total_nnz,avg_components_per_doc,original_memory_bytes,compressed_memory_bytes,component_memory_bytes,compression_ratio,num_queries,k_results,total_search_time_ms,avg_time_per_query_ms,avg_time_per_document_ns
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,NaN,128,8,8841823,28679,1060698636,119.96,8589934672,3983405094,0,2.156430,100,10,200349.251,2003492.51,226.593
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,Metis,128,8,8841823,28679,1060698636,119.96,8589934672,3707244174,0,2.317067,100,10,122421.478,1224214.77,138.457
0,/data2/knn_datasets/sparse_datasets/msmarco_v1...,GraphBisection,128,8,8841823,28679,1060698636,119.96,8589934672,3700201030,0,2.321478,100,10,125239.185,1252391.84,141.644

In [37]:
3700201030 / 1024**2

3528.786687850952

In [40]:
4531762589 / 1024**3 - 2646522062 / 1024**3

1.7557670613750815

2.464765740558505