In [1]:
import pandas as pd

In [2]:
import os

In [3]:
base_dir = "../my_codec_logs/"
all = []
for item in filter(lambda x: x.endswith(".tsv") and "partitioned" not in x, os.listdir(base_dir)):
    all.append(pd.read_csv(os.path.join(base_dir, item), sep="\t"))

In [4]:
all_df = pd.concat(all)

In [5]:
all_df['avg_time_per_query_ms'] = all_df['avg_time_per_query_ms'] / 1000

In [3]:
1187750904 / 35218632

33.72507211523718

In [1]:
1432353816

35218632

In [6]:
all_df[['codec_type', 'component_memory_bytes', 'compressed_memory_bytes', 'avg_time_per_query_ms']]

,codec_type,component_memory_bytes,compressed_memory_bytes,avg_time_per_query_ms
0,VByteLe,1301604336,3493736240,17474.97076
0,Gamma,1397135184,3589267088,17839.44658
0,VByteBe,1301604336,3493736240,16539.75866
0,Delta,1303766888,3495898792,17289.79368
0,Zeta,1152532272,3344664176,17530.61225

In [24]:
partitioned = pd.read_csv(os.path.join(base_dir, "partitioned.tsv"), sep="\t")
partitioned ['avg_time_per_query_ms'] = partitioned ['avg_time_per_query_ms'] / 1000

In [25]:
all_df['compressed_memory_bytes'] - all_df['component_memory_bytes']

0    2192131904
0    2192131904
0    2192131904
0    2192131904
0    2192131904
dtype: int64

In [26]:
partitioned['component_memory_bytes'] = partitioned['compressed_memory_bytes'] - 2192131904

In [27]:
partitioned[[ 'component_memory_bytes', 'compressed_memory_bytes', 'avg_time_per_query_ms']]

   component_memory_bytes  compressed_memory_bytes  avg_time_per_query_ms
0              1515112270               3707244174             1176.92411

In [29]:
1152532272 / 1515112270

0.7606910027862159